export const columns = [
  { name: "IMIĘ", uid: "name" },
  { name: "ROLA", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "AKCJE", uid: "actions" },
];
export const users = [
  {
    id: 1,
    name: "Tomasz Kowalski",
    role: "CEO",
    team: "Zarząd",
    status: "aktywny",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tomasz.kowalski@ambro.dev.com",
  },
  {
    id: 2,
    name: "Zofia Nowak",
    role: "Senior Developer",
    team: "Deweloperzy",
    status: "wstrzymane",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zofia.nowak@ambro.dev.com",
  },
  {
    id: 3,
    name: "Joanna Falkowska",
    role: "Senior Developer",
    team: "Deweloperzy",
    status: "aktywny",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "joanna.falkowska@ambro.dev.com",
  },
  {
    id: 4,
    name: "Wojtek Matuszewski",
    role: "Menadżer PR",
    team: "Marketing",
    status: "wakacje",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "wojtek.matuszewski@ambro.dev.com",
  },
  {
    id: 5,
    name: "Krystyna Klimek",
    role: "Menedżer Sprzedaży",
    team: "Sprzedaż",
    status: "aktywny",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "krystyna.klimek@ambro.dev.com",
  },
  {
    id: 6,
    name: "Adam Nowak",
    role: "CEO",
    team: "Zarządzanie",
    status: "aktywny",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "adam.nowak@ambro.dev.com",
  },
  {
    id: 10,
    name: "Alicja Kowalska",
    role: "Kierownik Sprzedaży",
    team: "Sprzedaż",
    status: "aktywny",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "alicia.kowalska@ambro.dev.com",
  },
  {
    id: 8,
    name: "Jan Nowicki",
    role: "Starszy Programista",
    team: "Rozwój",
    status: "aktywny",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jan.nowicki@ambro.dev.com",
  },
  {
    id: 7,
    name: "Zofia Wojciechowska",
    role: "Kierownik Techniczny",
    team: "Rozwój",
    status: "wstrzymane",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zofia.wojciechowska@ambro.dev.com",
  },
  {
    id: 9,
    name: "Michał Nowakowski",
    role: "Menedżer Społeczności",
    team: "Marketing",
    status: "urlop",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "michal.nowakowski@ambro.dev.com",
  },
  {
    id: 11,
    name: "Ewa Krawczyk",
    role: "CEO",
    team: "Zarządzanie",
    status: "aktywny",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "ewa.krawczyk@ambro.dev.com",
  },
  {
    id: 12,
    name: "Piotr Majewski",
    role: "Kierownik Sprzedaży",
    team: "Sprzedaż",
    status: "aktywny",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "piotr.majewski@ambro.dev.com",
  },
  {
    id: 13,
    name: "Joanna Adamczyk",
    role: "Starszy Programista",
    team: "Rozwój",
    status: "aktywny",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "joanna.adamczyk@ambro.dev.com",
  },
  {
    id: 14,
    name: "Krzysztof Woźniak",
    role: "Kierownik Techniczny",
    team: "Rozwój",
    status: "wstrzymane",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "krzysztof.wozniak@ambro.dev.com",
  },
  {
    id: 15,
    name: "Anna Kwiatkowska",
    role: "CEO",
    team: "Zarządzanie",
    status: "aktywny",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "anna.kwiatkowska@ambro.dev.com",
  },
  {
    id: 16,
    name: "Marcin Nowicki",
    role: "Kierownik Sprzedaży",
    team: "Sprzedaż",
    status: "aktywny",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "marcin.nowicki@ambro.dev.com",
  },
];
